language: node_js
node_js:
  - '10'

cache: yarn

before_install:
  # Use latest Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn build

before_deploy:
  - curl -sSL https://raw.githubusercontent.com/47ng/revelio/master/scripts/get.sh | bash
  - revelio generate -p ./build -u https://penelopebuckley.com
  - echo !.well-known > ./build/.surgeignore
  - cat ./build/.well-known/revelio.json

deploy:
  provider: surge
  project: ./build
  domain: https://penelopebuckley.com
  skip_cleanup: true
  on: master
